apiVersion: v1
kind: Service
metadata:
  name: product-website
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30022
  type: NodePort
  selector:
    module: web-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      module: web-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        module: web-server
    spec:
      containers:
      - image: test_website
        imagePullPolicy: IfNotPresent
        name: container-webapp
        ports:
        - containerPort: 80
      - image: test_product
        imagePullPolicy: IfNotPresent
        name: container-product
        ports:
        - containerPort: 9876

