version: "3"

services:
    product-service:
        image: amithapa/sampleapp
        ports:
            - 5001:80
    website:
            image: amithapa/samplewebsite
            ports:
                    - 5000:80
            depends_on:
                    - product-service
            deploy:
                        replicas: 2
    visualizer:
                image: dockersamples/visualizer:stable
                ports:
                        - "8082:8080"
                volumes:
                        - "/var/run/docker.sock:/var/run/docker.sock"
                deploy:
                        placement:
                                constraints: [node.role == manager]
